# https://docs.github.com/en/actions/concepts/workflows-and-actions/workflows
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
# https://vercel.com/kb/guide/how-can-i-use-github-actions-with-vercel

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test: # just a name for this job
    runs-on: ubuntu-slim # More lightweight than ubuntu-latest

    steps: # steps execute synchronously (step by step)
      - name: Checkout code
        uses: actions/checkout@v4 # github action default to clone repo into the CI runner

      - name: Setup Node.js
        uses: actions/setup-node@v4 # install node
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # ci -- clean install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

  deploy:
    runs-on: ubuntu-slim
    needs: build-and-test # Safety: Only deploy if tests pass
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}